default_stages: [pre-commit]
repos:
  - repo: local
    hooks:
      - id: printf-log-formatter
        name: printf-log-formatter
        entry: uv run printf-log-formatter
        language: system
        types: [ python ]
        args:
          - --log-level=debug

      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        types: [ python ]

      - id: ruff-check
        name: ruff-check
        entry: uv run ruff check
        language: system
        types: [ python ]
        args: [ --fix ]

      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        types: [ python ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: mixed-line-ending
      - id: check-added-large-files

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        types: [ python ]
        args: [ "--py313-plus"]
