default_stages: [commit, push]
repos:
  - repo: local
    hooks:
      - id: printf-log-formatter
        name: printf-log-formatter
        entry: printf-log-formatter
        language: system
        types: [ python ]
        args:
          - --log-level=debug

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]

      - id: black
        name: black
        entry: black
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: mixed-line-ending
      - id: check-added-large-files

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        types: [ python ]
        args: [ "--py3-plus", "--py36-plus", "--py37-plus", "--py38-plus", "--py39-plus", "--py310-plus"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
      - id: poetry-check

  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
      - id: poetry-check

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - redis
          - pytest
          - types-redis

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.403
    hooks:
    - id: pyright
      additional_dependencies:
        - pydantic
        - redis
        - pytest
        - types-redis
