name: test

on:
  pull_request:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: "3.11.x"

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - run: pip install pre-commit
      - uses: actions/cache@v4.2.3
        id: pre-commit-cache
        with:
          path: ~/.cache/pre-commit
          key: key-0
      - run: pip install printf-log-formatter black isort
      - run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: actions/cache@v4.2.3
        id: poetry-cache
        with:
          path: ~/.local
          key: ${{ matrix.python-version }}-0
      - uses: snok/install-poetry@v1.4.1
        with:
          virtualenvs-create: false
          version: latest
      - uses: actions/cache@v4.2.3
        id: cache-venv
        with:
          path: .venv
          key: ${{ hashFiles('**/poetry.lock') }}-${{ matrix.python-version }}-0
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip
          poetry install --no-interaction --no-root --with=development
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: redis-tools
          version: 0
      - name: Run tests
        run: |
          docker compose up -d
          chmod +x ./setup-cluster.sh
          ./setup-cluster.sh
          source .venv/bin/activate
          coverage run -m pytest tests
          coverage xml
          coverage report
