name: test

on:
  pull_request:
  push:
    branches:
      - main

env:
  MISE_OVERRIDE_CONFIG_FILENAMES: "mise.ci.toml"

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: jdx/mise-action@v2
        with:
          cache: true
      - name: Install dependencies
        run: |
          mise run install-uv-ci
      - name: Lint
        run: mise run lint-ci
      - name: Pre-commit
        run: mise run pre-commit-ci

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: jdx/mise-action@v2
        with:
          cache: true
      - name: Install dependencies
        run: |
          mise install redis-cli
          mise use redis-cli
          mise run install-uv-ci

      - name: Override Python version
        run: mise use python@${{ matrix.python-version }}
      - name: Setup test environment
        run: mise run test-setup-ci
      - name: Run tests
        run: mise run test-ci
      - name: Cleanup test environment
        if: always()
        run: mise run test-teardown-ci
